name: Build env images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          file: env.dockerfile
          context: backend
          platforms: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/blueforest:env